[package]
name = "ttv"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = { version = "3.2.1", default-features = false, features = ["cpu", "process"] }
crossterm = "0.26.1"


